### ISSUE TITLE
Snake doesn't show

### ISSUE THREAD

**Issue by CodeDiseaseDev** [janbodnar/Java-Snake-Game#11]
When I run the game I see a blank window then not long after I see "Game Over" 
<img width="685" alt="Screen Shot 2021-08-04 at 10 25 21 am" src="https://user-images.githubusercontent.com/70626250/128102895-630990c4-ddc3-42e8-8466-49fef14d81a4.png">
I'm not sure if this has anything to do with me being on a Mac.

**Comment by CodeDiseaseDev** [comment]
Sorry, I was being an idiot!
I didn't add the images...

**Comment by lucialam172** [comment]
It has been released now, correct? So, this should be updated to
[https://github.com/lucialam172/dark-kitchen-cabinets](https://github.com/lucialam172/dark-kitchen-cabinets)
[https://github.com/lucialam172](https://github.com/lucialam172)
[https://lucialam172.github.io/dark-kitchen-cabinets](https://lucialam172.github.io/dark-kitchen-cabinets)
