### ISSUE TITLE
Aplicación de principios SOLID (Recomendaciones)

### ISSUE THREAD

**Issue by sbenalca** [janbodnar/Java-Snake-Game#5]
**1. Justificación de Posibles violaciones a principio SRP**

Para solucionar las violaciones en este principio es necesario crear una clase que haga de controlador del juego, a la que llamaremos “Controlador”. Dentro de esta clase agregaremos todos los métodos relacionados con las reglas del juego, generación de componentes externos a la generación del tablero o personaje (la serpiente). Dentro de tablero dejaremos los métodos relacionados a la modificación del tablero y relacionados.

**2. Justificación de Posibles violaciones a principio OCP**

Se solucionaría este principio al crear nuevas clases e interfaces tales como un controlador de juego, una clase del juego principal y clases específicas para manejar los objetos serpiente (Snake) y tablero (Board).

**3. Justificación de Posibles violaciones a principio LSP**

Al crear una clase abstracta llamada Game(juego) en la cual se inserten los componentes principales de un juego y los métodos más generales, se podría crear la relación de herencia con la nueva clase SanakeGame que extiende de Game.

**4. Justificación de Posibles violaciones a principio ISP**

Al implementar nuevas interfaces que manejen cada uno de los métodos del juego categorizándolos por tipo, se puede satisfacer este principio. En este caso la creación de una interfaz que contenga los métodos específicos del juego de SnakeGame sería suficiente. Aunque se podría mejorar en caso de implementar una interfaz específica tanto para métodos del componente Board como otra para Snake.

**5. Justificación de Posibles violaciones a principio DIP**

Al crear la clase abstracta game, y crear la interfaz GameSessionGenerator se mejora la comunicación entre partes del sistema, separando por niveles de interacción a los métodos generales de un juego en la clase abstract y a los métodos específicos de 

![Java-Snake-Game](https://user-images.githubusercontent.com/37081244/88009646-a5b3eb80-cad8-11ea-8937-425a7c881c8e.jpeg)

**Comment by janbodnar** [comment]
This is overengineering. The game is targeted at beginner programmers and such a structure would be difficult for them to understand.
